from pydantic import BaseModel, Field
from typing import List, Optional

class QualityReport(BaseModel):
    complexity_score: float
    maintainability_score: float
    security_score: float
    performance_score: float
    overall_grade: str
    recommendations: List[str]

class CodeGeneration(BaseModel):
    query: str
    language: str
    generated_code: Optional[str] = Field(None, description="The code generated by the model")
    title: Optional[str] = Field(None, description="Title for the generated code")


class ExtraGeneration(BaseModel):
    unit_tests: Optional[str] = Field(None, description="Unit tests for the generated code")
    documentation: Optional[str] = Field(None, description="Documentation for the generated code")
    quality_report: Optional[QualityReport] = Field(None, description="Quality report for the generated code")


class GenerateTestsRequest(BaseModel):
    code: str = Field(..., description="The source code to generate tests for")
    language: str = Field(..., description="Programming language (python, javascript, java, ...)")
    framework: str = Field(..., description="Testing framework (pytest, unittest, jest, ...)")


class GenerateTestsResponse(BaseModel):
    ok: bool = Field(True, description="Whether the operation was successful")
    tests: str = Field(..., description="Generated unit test code")
    language: str = Field(..., description="Programming language")
    framework: str = Field(..., description="Testing framework")
    notes: List[str] = Field(default_factory=list, description="Optional notes or TODOs")