from pydantic import BaseModel, Field
from typing import List, Optional

class QualityReport(BaseModel):
    complexity_score: float
    maintainability_score: float
    security_score: float
    performance_score: float
    overall_grade: str
    recommendations: List[str]

class CodeGeneration(BaseModel):
    query: str
    language: str
    generated_code: Optional[str] = Field(None, description="The code generated by the model")
    title: Optional[str] = Field(None, description="Title for the generated code")


class ExtraGeneration(BaseModel):
    unit_tests: Optional[str] = Field(None, description="Unit tests for the generated code")
    documentation: Optional[str] = Field(None, description="Documentation for the generated code")
    quality_report: Optional[QualityReport] = Field(None, description="Quality report for the generated code")


class GenerateTestsRequest(BaseModel):
    code: str = Field(..., description="The source code to generate tests for")
    language: str = Field(..., description="Programming language (python, javascript, java, ...)")
    framework: str = Field(..., description="Testing framework (pytest, unittest, jest, ...)")


class GenerateTestsResponse(BaseModel):
    ok: bool = Field(True, description="Whether the operation was successful")
    tests: str = Field(..., description="Generated unit test code")
    language: str = Field(..., description="Programming language")
    framework: str = Field(..., description="Testing framework")
    notes: List[str] = Field(default_factory=list, description="Optional notes or TODOs")


class GenerateDocsRequest(BaseModel):
    code: str = Field(..., description="Source code to document")
    language: Optional[str] = Field(None, description="Programming language of the code")
    project_name: Optional[str] = Field(
        None, description="Optional project or feature name to use inside the documentation"
    )


class GenerateDocsResponse(BaseModel):
    ok: bool = Field(True, description="Whether the documentation generation succeeded")
    filename: str = Field(..., description="Suggested filename for the generated markdown")
    content: str = Field(..., description="Markdown documentation body")
    notes: List[str] = Field(default_factory=list, description="Optional notes or TODOs")


class QualityMetricResult(BaseModel):
    name: str = Field(..., description="Metric name, e.g., Cyclomatic Complexity")
    score: int = Field(..., ge=0, le=100, description="Numeric score between 0 and 100")
    letter: str = Field(..., description="Letter grade (A+, A, B, ...)")
    explanation: str = Field(..., description="Short explanation for the score")


class QualityReportRequest(BaseModel):
    code: str = Field(..., description="Source code to evaluate")
    language: Optional[str] = Field(None, description="Programming language for contextual messaging")


class QualityReportResponse(BaseModel):
    ok: bool = Field(True, description="Whether quality analysis succeeded")
    final_score: int = Field(..., ge=0, le=100, description="Aggregated score between 0 and 100")
    final_grade: str = Field(..., description="Letter score summarizing all metrics")
    metrics: List[QualityMetricResult] = Field(..., description="List of evaluated metrics")
    suggestions: List[str] = Field(default_factory=list, description="Actionable suggestions or notes")